import type { Metadata } from "next";
import "../../globals.css";
import Navbar from "@/components/utils/Navbar";
;

export const metadata: Metadata = {
    title: "chat.ai | Chat",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <Navbar />
            <main className="flex flex-col py-10 lg:px-0 px-4">
                {children}
            </main>
        </div>

    );
}
