import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/utils/Footer";

;

export const metadata: Metadata = {
  title: "chat.ai | home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen overflow-y-hidden ">
        {children}
        <Footer />
      </body>
    </html>
  );
}
