import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/utils/Navbar";
import Footer from "@/components/utils/Footer";
;

export const metadata: Metadata = {
  title: "chat.ai | Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="flex flex-col py-10">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
